name: pubtator
dependencies:
- python=3.8
- lxml=4.4
- tqdm
- requests
- pandas=0.25.3
- pip
- pip:
    - git+https://github.com/en-dash/PyBioC@a21bd181ce3b89de791db4bb7db6ca1c48167648
    - ratelimit